bit-bots/bitbots_behavior

bitbots_head_behavior/src/bitbots_head_behavior/head_node.py

currently, the publishing topic is "/DynamixelController/command" this sets it to "/head_motor_goals".

fixing the head motor goals publishing topic

---

bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_block_position.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_defense_position.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_role_position.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/ball_in_defensive_area.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

With this PR, I propose some improvements for positioning stuff. Mainly, i renamed variables and implemented an initial version (We do need a solution for two defensive players!) of GoToDefensePosition.

Positioning improvements

---

bitbots_body_behavior/src/bitbots_body_behavior/actions/kick_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/look_at.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/search_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd
bitbots_head_behavior/config/head_config.yaml
bitbots_head_behavior/src/bitbots_head_behavior/actions/search_pattern.py
bitbots_head_behavior/src/bitbots_head_behavior/decisions/head_mode_decision.py
bitbots_head_behavior/src/bitbots_head_behavior/head_behavior.dsd

This pull request contains actions for the penalty kick behavior to seperate this from the actions of used during the game. Furthermore the dsd path for the penalty kick was adapted. This pull request belongs to the same named pull request in humanoid_league_msgs

Penalty kick behavior

---

bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

With this changes it is possible to reevaluated the just unpenalized decision

Unpenalized decision

---

bitbots_blackboard/src/bitbots_blackboard/capsules/blackboard_capsule.py
bitbots_blackboard/src/bitbots_blackboard/capsules/head_capsule.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/circle_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd
bitbots_head_behavior/src/bitbots_head_behavior/actions/look_at.py
bitbots_head_behavior/src/bitbots_head_behavior/decisions/post_seen.py

moving transform listeners into blackboards

---

bitbots_blackboard/src/bitbots_blackboard/blackboard.py
bitbots_blackboard/src/bitbots_blackboard/capsules/kick_capsule.py
bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/src/bitbots_body_behavior/actions/kick_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

The dynamic kick uses a separate action to allow easy switching between static and dynamic kicks. Also, a separate capsule in the blackboard was added.

Use dynamic kick in the body behavior

---

bitbots_blackboard/src/bitbots_blackboard/capsules/pathfinding_capsule.py
bitbots_body_behavior/src/bitbots_body_behavior/body_behavior.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/aligned_to_goal.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

This pull request closes #20. A new decision is used because of a higher variability. For example, the new decision is only included in the DSD before the kicking decision when localization is used or a goal is seen.

Decision AlignedToGoal

---

bitbots_body_behavior/launch/rviz_behavior_test.launch

just moves a launch file into the correct folder

behavior: move rviz test launch from HL_visualization

---

bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/aligned_to_goal.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

this will remove oscillation in the pathfinding and lead to a stable approaching of the ball.

Adds close ball target

---

bitbots_body_behavior/src/bitbots_body_behavior/decisions/just_unpenalized.py

closes [dynamic_stack_decider#20](https://github.com/bit-bots/dynamic_stack_decider/issues/20)

body_behavior: fix just_unpenalized visualization bug

---

bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py

Handles transform problems in the goal handling
Handling transform errors with a fallback option and thereby preventing the body behavior from dying instantly

Handles transform problems in the goal handling

---

bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/src/bitbots_body_behavior/decisions/aligned_to_goal.py

moves the alignment param of AlignedToGoal into the config file
move the alignment param of AlignedToGoal into the config file

moves the alignment param of AlignedToGoal into the config file

---

bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

This reverts commit 8bb6bbe7568412c07ce09c0a3abe911b41b4f421 that removed the dynamic kick in the behavior.

Body Behavior: Reenable Dynamic Kick

---

bitbots_body_behavior/launch/rviz_behavior_test.launch
bitbots_body_behavior/package.xml

behavior: fix rviz launch file due to changes in odometry

---

bitbots_blackboard/src/bitbots_blackboard/capsules/head_capsule.py
bitbots_head_behavior/package.xml
bitbots_head_behavior/src/bitbots_head_behavior/actions/search_pattern.py

Fix collisions with the head and the shoulder, by reducing the width of the lowest scanline.
Closes issue #55

Head Behavior: Fix head shoulder collision

---

bitbots_body_behavior/launch/body_behavior.launch
bitbots_body_behavior/launch/rviz_behavior_test.launch
bitbots_body_behavior/launch/simple_behavior.launch
bitbots_body_behavior/package.xml
bitbots_head_behavior/launch/head_behavior.launch
bitbots_head_behavior/package.xml

remove respawn

---

bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py
bitbots_body_behavior/launch/rviz_behavior_test.launch
bitbots_body_behavior/package.xml
bitbots_body_behavior/scripts/show_world_model_objects.py

A publisher for markers to visualize the ball and the goalposts of the robots world model was added.
There is no related issue.

Bitbots_body_behavior: Feature/visualize world model

---

bitbots_body_behavior/package.xml
bitbots_body_behavior/scripts/backup_behavior.py
bitbots_body_behavior/scripts/show_world_model_objects.py
bitbots_body_behavior/src/bitbots_body_behavior/body_behavior.py
bitbots_head_behavior/package.xml
bitbots_head_behavior/scripts/testHeadBehaviour.py
bitbots_head_behavior/scripts/test_look_at.py
bitbots_head_behavior/src/bitbots_head_behavior/head_node.py

This pull request updates all shebangs to python3 as we will discuss in our weekly.

Update shebangs to python3

---

bitbots_blackboard/src/bitbots_blackboard/capsules/game_status_capsule.py
bitbots_body_behavior/package.xml
bitbots_body_behavior/src/bitbots_body_behavior/decisions/secondary_state_decider.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

It is now possible to react to the secondary game state such as a free kick. For this, decisions for the secondary game state have been added and this is included in the DSD.
#22

Body Behavior: Secondary Game States

---

bitbots_blackboard/package.xml
bitbots_blackboard/src/bitbots_blackboard/blackboard.py
bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py

The class variable goal_width is initialized in the WorldModelCapsule.
#78

Blackboard: Goal_width attribute

---

bitbots_blackboard/package.xml
bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py

Changes to a frame based pose
This solves #91

Body Behavior frame based pose

---

bitbots_blackboard/package.xml
bitbots_body_behavior/src/bitbots_body_behavior/decisions/localization.py

Reevaluates the localization decision. This is important when using localization precision estimates

reevaluate localization decision

---

bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/package.xml
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_role_position.py

Introduces more hardcoded positions for flexible robot position assignment
This solves issue #6 but poses issue #89  for later.

BodyBehavior: 4th position

---

bitbots_body_behavior/package.xml
bitbots_body_behavior/src/bitbots_body_behavior/decisions/goal_seen.py

This reverts a Hot-Fix which should not be used anymore as pointed out in #66.
Fixes #66

Goal lost time

---

bitbots_head_behavior/config/head_config.yaml
bitbots_head_behavior/package.xml
bitbots_head_behavior/src/bitbots_head_behavior/actions/look_at.py

Uses config params in look_at.py

Use config params in look_at.py

---

bitbots_blackboard/package.xml
bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py
bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/package.xml
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_block_position.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

This is supposed to solve issue #15 with the go to block position action.

use block position in DSD

---

bitbots_body_behavior/package.xml
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_block_position.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_defense_position.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_role_position.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/ball_dangerous.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/ball_in_defensive_area.py

Fix param restructure

---

bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/package.xml

Removes an unused parameter which was just confusing.

Remove unused param

---

bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py
bitbots_body_behavior/package.xml
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_ball.py

Fixes the alignment to the map goal
Addresses #106 but does not solve it.

fix map goal alignment

---

bitbots_body_behavior/package.xml
bitbots_body_behavior/src/bitbots_body_behavior/actions/align_to_goal.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/aligned_to_goal.py

Fixes the AlignedToGoal Decision
Every position was accepted

Fix aligned to goal

---

bitbots_blackboard/package.xml
bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py
bitbots_body_behavior/package.xml
bitbots_body_behavior/src/bitbots_body_behavior/actions/circle_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/kick_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/ball_kick_area.py

This adapts the behavior to use the `ball_approach_frame` introduced in https://github.com/bit-bots/bitbots_misc/pull/87.

use ball_approach_frame to approach the ball

---

bitbots_head_behavior/config/head_config.yaml

Add new params for the wider FOV.
#119

Add new params

---

bitbots_blackboard/src/bitbots_blackboard/capsules/pathfinding_capsule.py
bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/search_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/stand.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd
bitbots_head_behavior/config/head_config.yaml

- Remove weird timestamp
- Use correct timing for the query of the ball in the approach frame
- Use `StandAndWait` to stabilize before kick 
- Remove duplicate of the movebase thresholds
- Use the correct angle for the robot alignment on the map

Integration test fixes

---

bitbots_head_behavior/launch/test.launch

Adds ability to test head behavior in rviz

head: change test launch for viz

---

bitbots_blackboard/src/bitbots_blackboard/capsules/game_status_capsule.py

Now listens correctly to allowedToMove

---

bitbots_body_behavior/src/bitbots_body_behavior/actions/kick_ball.py

This passes the actual relative position of the ball to the kick.
Closes #123.

Give actual ball position to kick

---

Jenkinsfile
bitbots_blackboard/.rdmanifest
bitbots_blackboard/rosdoc.yaml
bitbots_body_behavior/rosdoc.yaml
bitbots_head_behavior/rosdoc.yaml

add ci config for bitbots_blackboard and `.rdmanifest` file

---

bitbots_blackboard/src/bitbots_blackboard/blackboard.py
bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py
bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/src/bitbots_body_behavior/body_behavior.py

make ball twist available in world model capsule
this solves #95

Ball twist in  world_model_capsule init

---

bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

Before kicking, the robot now looks forward
Resolves #117
~- [ ] Run `catkin build`~
~- [ ] Write documentation~
~- [ ] Create issues for future work~
~- [ ] Test on the robot~

Looks forward on kick

---

bitbots_blackboard/src/bitbots_blackboard/capsules/team_data_capsule.py

This fixes a NameError in the team data callback.

Fix NameError in team data callback

---

bitbots_head_behavior/CMakeLists.txt
bitbots_head_behavior/src/collision_checker.cpp

Same as bit-bots/bitbots_motion#256.

use -Wall in head behavior

---

bitbots_body_behavior/src/bitbots_body_behavior/body_behavior.py
bitbots_head_behavior/scripts/testHeadBehaviour.py
bitbots_head_behavior/src/bitbots_head_behavior/head_node.py

https://github.com/bit-bots/bitbots_misc/pull/122

change to new rate implementation

---

bitbots_head_behavior/src/bitbots_head_behavior/head_node.py

To make head react faster and smoother

increase head behavior rate

---

bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py

* Cleanup ball twisted handling
* Make it work that the head behavior runs without the body behavior (e.g. for demos)

Cleanup ball twisted handling

---

bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py
bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

Dont reeval during kick with the new dsd feature

---

bitbots_body_behavior/src/bitbots_body_behavior/decisions/secondary_state_decider.py

fix deciding penalty kick

---

bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py
bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/package.xml
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/kick_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/body_behavior.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

* Adds a gradient behavior
* Adds sidekicks based on local cost map
This is still very WIP

Gradient behavior

---

bitbots_body_behavior/package.xml

Add ros_numpy dep

---

bitbots_body_behavior/src/bitbots_body_behavior/decisions/game_state_decider.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/secondary_state_decider.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

This changes some things in the code so that the DSD GUI works with body behavior. This is only a temporary hacky fix. Fixing the GUI itself would be preferred, but needs more time. This way we can use it right now. Todos were added so that the hacks can be removed later on.
https://github.com/bit-bots/dsd-gui/issues/3
https://github.com/bit-bots/dsd-gui/issues/4

changed some code to make gui work

---

bitbots_head_behavior/config/head_config.yaml

https://github.com/bit-bots/wolfgang_robot/pull/173

adapt max angles for head pattern

---

bitbots_blackboard/src/bitbots_blackboard/capsules/game_status_capsule.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/secondary_state_decider.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

Currently we did not listen to the secondary game mode and therefore handled things as direct kicks or throw ins wrong
https://github.com/bit-bots/humanoid_league_misc/pull/85

body: fix secondary game mode

---

bitbots_blackboard/src/bitbots_blackboard/capsules/game_status_capsule.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/secondary_state_decider.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

* Adds some getters to the game state
* Fixes the penalty kick behavior

Fix penalty kick behavior

---

bitbots_blackboard/src/bitbots_blackboard/blackboard.py
bitbots_body_behavior/config/animations.yaml
bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/src/bitbots_body_behavior/actions/play_animation.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/ball_dangerous.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

Lets goalie throw itself to the sides
needs https://github.com/bit-bots/wolfgang_robot/pull/177

Goalie falling

---

bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

* Waits a few seconds after the penalty

Wait after penalty

---

bitbots_blackboard/src/bitbots_blackboard/blackboard.py
bitbots_blackboard/src/bitbots_blackboard/capsules/game_status_capsule.py
bitbots_body_behavior/config/animations.yaml
bitbots_body_behavior/src/bitbots_body_behavior/actions/play_animation.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/goal_scored.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

* Execute cheer during the ready state if a goal was kicked by our team.
#39 #70

Let the goalie cheere if there is a goal by our team

---

bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py

fix ball twist publisher none error
This should solve #175

fix ball twist publisher none error

---

bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py
bitbots_body_behavior/config/body_behavior.yaml

refactoring costmaps to use parameters and class fields

refactoring costmaps to use parameters

---

bitbots_blackboard/src/bitbots_blackboard/capsules/game_status_capsule.py
bitbots_blackboard/src/bitbots_blackboard/capsules/team_data_capsule.py
bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py
bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/src/bitbots_body_behavior/actions/change_action.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/change_role.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_pass_position.py
bitbots_body_behavior/src/bitbots_body_behavior/body_behavior.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/closest_to_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/goalie_handling_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/pass_started.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

Introduces improvements in the behavior via team comm
needs https://github.com/bit-bots/humanoid_league_msgs/pull/31 and https://github.com/bit-bots/humanoid_league_misc/pull/91

Team comm in behavior

---

bitbots_blackboard/src/bitbots_blackboard/blackboard.py

Follow-up on #169, remove usage of global namespaces.

Fix usage of global namespace

---

bitbots_blackboard/package.xml
bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py
bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/package.xml
bitbots_body_behavior/src/bitbots_body_behavior/body_behavior.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

* Use points from point cloud instead of the costmap2d for the obstacle input
bit-bots/bitbots_navigation/pull/137

Handle obstacles via Point Cloud

---

bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_defense_position.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_pass_position.py

* Use non-gradient-based orientation
* More consistent position selection
* Maximum x position parameter, so the robot doesn't move behind the opponent's goal.

Fix support positioning

---

bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

Disables reevaluation when walkready animation is played after penalty

---

bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py
bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/src/bitbots_body_behavior/decisions/ball_close.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

* New params
* Reevaluate the placement before the kick. This may lead to a longer more unstable approach, but we have the correct placement if the ball moves.
* Add ball again as an obstacle if it is not only far away, but also if it is sideways or behind.
* Add ball angle to world model capsule
* Another head pattern to better detect other robots while kicking. Also, the "look at ball" got stuck if we were at a max position due to the self-collision.

Change ball reapproach

---

bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

* Execute walkready in the init state to go in walkready in the second half of the game.
Based on #197

Walkready in behavior

---

bitbots_body_behavior/config/body_behavior.yaml

increase defensive area so that the defensive player defends its full half instead of only half the half :D

increase defensive area

---

bitbots_blackboard/src/bitbots_blackboard/capsules/head_capsule.py
bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/src/bitbots_body_behavior/decisions/ball_kick_area.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd
bitbots_head_behavior/config/head_config.yaml
bitbots_head_behavior/src/bitbots_head_behavior/actions/look_at.py
bitbots_head_behavior/src/bitbots_head_behavior/head_behavior.dsd
bitbots_head_behavior/src/bitbots_head_behavior/head_node.py

* Use overlapping thresholds for kick area
* Fix stuck head behavior

New kick area

---

bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

Fixes defender issues from previous test game.

fix defender

---

bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

Small fix for going into walkready

fix walkready in init

---

bitbots_body_behavior/src/bitbots_body_behavior/actions/play_animation.py

* Same check for a finished animation as in the HCM
* Don't count a running animation as finished

Fix animation finished

---

bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/src/bitbots_body_behavior/actions/kick_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

Chose direction of penalty kick based on gradient map

penalty shoot direction

---

bitbots_blackboard/src/bitbots_blackboard/blackboard.py
bitbots_body_behavior/config/animations.yaml
bitbots_body_behavior/src/bitbots_body_behavior/actions/play_animation.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/turn.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/ball_dangerous.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

- fix goalie placing during standard situations
- fix goalie going back to walkready after cheering
- improve goalie in penalty shootout
- improve goalie turning when ball is not seen

various goalie fixes

---

bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

fix broken merge

---

bitbots_body_behavior/src/bitbots_body_behavior/actions/stand.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/ball_dangerous.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

- Fix reevaluation of BallDangerous
- remove some unnecessary pauses

Small fixes for penalty kick goalie

---

bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

improve accepting passes

---

bitbots_blackboard/src/bitbots_blackboard/async_service.py
bitbots_blackboard/src/bitbots_blackboard/blackboard.py
bitbots_blackboard/src/bitbots_blackboard/capsules/pathfinding_capsule.py
bitbots_blackboard/src/bitbots_blackboard/capsules/team_data_capsule.py
bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py
bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/scripts/fake_plan.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/body_behavior.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/closest_to_ball.py

time to ball calculation

---

bitbots_blackboard/src/bitbots_blackboard/blackboard.py
bitbots_blackboard/src/bitbots_blackboard/capsules/team_data_capsule.py
bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py
bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/src/bitbots_body_behavior/decisions/closest_to_ball.py

* Get poses from the team data
* Add low-cost region 1 meter away from the teammates in the direction of the goal
* Publish costmap for rviz

Add low cost region to costmap for passes

---

bitbots_body_behavior/config/body_behavior.yaml

lower time to remember path to ball for time_to_ball

---

bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_corner_kick_position.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_defense_position.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_role_position.py

stand further back if the enemy has kickoff as supporter

---

bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

dont change duty anymore, the problem why we had to change it was fixed in  https://github.com/bit-bots/bitbots_behavior/commit/0d700e1938864b4468d57b841cb159ce2ff609ae (in bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_defense_position.py)

dont change duty since it breaks things

---

bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py
bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/src/bitbots_body_behavior/body_behavior.py
bitbots_head_behavior/launch/head_behavior.launch
bitbots_head_behavior/launch/head_behavior_standalone.launch
bitbots_head_behavior/src/bitbots_head_behavior/head_node.py

Integrate ball filter into behavior
#131 
This only works in combination with https://github.com/bit-bots/bitbots_world_model/pull/21

ball_filter integration

---

bitbots_blackboard/CMakeLists.txt
bitbots_blackboard/package.xml
bitbots_blackboard/src/bitbots_blackboard/capsules/pathfinding_capsule.py
bitbots_blackboard/src/bitbots_blackboard/capsules/team_data_capsule.py
bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py
bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/src/bitbots_body_behavior/actions/forget_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_pass_position.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/kick_ball.py
bitbots_body_behavior/src/bitbots_body_behavior/actions/play_animation.py
bitbots_body_behavior/src/bitbots_body_behavior/body_behavior.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/aligned_to_goal.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/allowed_to_move.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/ball_kick_area.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/dribble_or_kick.py
bitbots_body_behavior/src/bitbots_body_behavior/decisions/kick_off_time_up.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd
bitbots_head_behavior/launch/head_behavior.launch
bitbots_head_behavior/launch/head_behavior_standalone.launch
bitbots_head_behavior/src/bitbots_head_behavior/head_node.py

- Forgets the ball in secondary state modes
- Resets ball filter
bit-bots/bitbots_world_model/pull/19

Forget ball in secondary state modes

---

bitbots_body_behavior/config/body_behavior.yaml
bitbots_body_behavior/src/bitbots_body_behavior/decisions/ball_dangerous.py
bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

* Change ball dangerous so that it doesn't activate instantly center

Fix ball dangerous for penalty shoots

---

bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

Improve goalie/defender hybrid based on observations from last game

hybrid and defender improvement

---

bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

currently only robo 1 does penalty shoots, this is bad because everyone should try and the robots that dont have the kick cant move anyways

its anyones penalty

---

bitbots_body_behavior/src/bitbots_body_behavior/main.dsd

revert goalie to be only goalie, goodbye hybrid

---

bitbots_body_behavior/config/body_behavior.yaml

* Tweak params for the adult match
https://github.com/bit-bots/humanoid_league_misc/pull/102

Adult size

---

bitbots_body_behavior/config/body_behavior.yaml

This reverts commit d87ffdf517d6175940aa5879c0b086e72f051af6.

Revert "Adult size behavior params"

---

bitbots_body_behavior/src/bitbots_body_behavior/body_behavior.py
bitbots_head_behavior/scripts/testHeadBehaviour.py
bitbots_head_behavior/src/bitbots_head_behavior/head_node.py

This reverts commit 0ea5dd1ff2fbcb95a6f187e542de4dc4c2524e7d.
Introduced in #156.
Remove bitbots_ros_patches as it is not needed anymore.

Revert "change to new rate implementation"

---

bitbots_body_behavior/config/body_behavior.yaml

This reverts pull request #252.

Revert "Merge pull request #252 from bit-bots/param/1v1_passive"

---

bitbots_head_behavior/launch/test.launch

Update test launch to vision_standalone
bit-bots/bitbots_vision/pull/308
bit-bots/bitbots_misc/pull/159

Update test launch to vision_standalone

---

bitbots_body_behavior/setup.py
bitbots_head_behavior/setup.py

- Add empty resource file to add packages to ament index

Fix deprication warnings

---

bitbots_blackboard/bitbots_blackboard/capsules/world_model_capsule.py

remove ball filtered

---

bitbots_body_behavior/bitbots_body_behavior/actions/go_to_role_position.py

load multiple defender positions

---

bitbots_blackboard/bitbots_blackboard/capsules/blackboard_capsule.py
bitbots_blackboard/bitbots_blackboard/capsules/game_status_capsule.py
bitbots_body_behavior/bitbots_body_behavior/actions/go_to_corner_kick_position.py
bitbots_body_behavior/bitbots_body_behavior/actions/go_to_defense_position.py
bitbots_body_behavior/bitbots_body_behavior/actions/go_to_role_position.py
bitbots_body_behavior/config/body_behavior.yaml

- Remove randomized offense position
- Add active and passive defense positions
- Simplify code
- Fix the global position number parameter

Fix global params and role positions

---

bitbots_body_behavior/bitbots_body_behavior/body_behavior.py
bitbots_head_behavior/bitbots_head_behavior/head_node.py

Updates usage of bitbots_moveit_bindings, see pull request there.

Update usage of bitbots_moveit_bindings

---

bitbots_head_behavior/bitbots_head_behavior/actions/look_at.py

- Fix traceback occuring during sim tests

Fix missing nesting in moveit bindings call

---

bitbots_blackboard/package.xml
bitbots_body_behavior/package.xml
bitbots_head_behavior/package.xml

to allow for new features like conditional depends accoring to rep [0149].
We use this to differentiate between dependencies required on robots and in
the simulation.
[149]: https://www.ros.org/reps/rep-0149.html

fix(package.xml): upgrade to version 3

---

bitbots_blackboard/bitbots_blackboard/capsules/costmap_capsule.py
bitbots_body_behavior/bitbots_body_behavior/main.dsd
bitbots_body_behavior/config/body_behavior.yaml

As the kick might not be super stable, we want to use dribbling instead.
Also no passing to teammates.
Shorten ball_lost_time.
#291

Change kick to dribble

---

bitbots_body_behavior/bitbots_body_behavior/body_behavior.py

Requires https://github.com/bit-bots/bitbots_misc/pull/222.

Use new bitbots_tf_listener

---

bitbots_blackboard/bitbots_blackboard/capsules/world_model_capsule.py

String is needed in error log.

Add string

---

bitbots_head_mover/config/head_config.yml
bitbots_head_mover/src/move_head.cpp

Smoothen head acceleration

---

bitbots_body_behavior/bitbots_body_behavior/actions/dribble_forward.py
bitbots_body_behavior/config/body_behavior.yaml

- Redo the math / params
- Tune it on the real robot

Rework dribbeling behavior

---

bitbots_blackboard/bitbots_blackboard/blackboard.py
bitbots_blackboard/bitbots_blackboard/capsules/world_model_capsule.py
bitbots_body_behavior/bitbots_body_behavior/actions/go_to.py
bitbots_body_behavior/bitbots_body_behavior/actions/walk.py
bitbots_body_behavior/bitbots_body_behavior/body_behavior.py
bitbots_body_behavior/bitbots_body_behavior/decisions/reached_goal.py
bitbots_body_behavior/bitbots_body_behavior/main.dsd
bitbots_body_behavior/bitbots_body_behavior/minimal.dsd
bitbots_body_behavior/launch/behavior.launch
bitbots_body_behavior/launch/behavior_standalone.launch
bitbots_body_behavior/launch/body_behavior.launch
bitbots_body_behavior/launch/simple_behavior.launch
bitbots_body_behavior/setup.py

Adds simple behavior (`minimal.dsd`) for drop in games.

Test simple gameready walkin

---

bitbots_blackboard/bitbots_blackboard/blackboard.py
bitbots_blackboard/bitbots_blackboard/capsules/world_model_capsule.py
bitbots_body_behavior/bitbots_body_behavior/actions/go_to.py

Fixes https://github.com/bit-bots/bitbots_behavior/issues/323

fix(pathplanning): explicit handling of empty poses after tf

---

bitbots_head_mover/launch/head_mover.launch

This does not solve but provides a solution for #324.

Respawn head mover when it dies

---

bitbots_body_behavior/bitbots_body_behavior/decisions/localization.py
bitbots_body_behavior/bitbots_body_behavior/main.dsd

to prevent jumping between LOW and HIGH leading to effects in the pathplanning, which negatively affected our walking behavior

fix(localization): add debounce to precision decision

---

bitbots_head_mover/CMakeLists.txt
bitbots_head_mover/src/move_head.cpp

- Reformat the head mover using an automated tool
- Always build head mover with debug to get a traceback for #324.

Reformat head mover and build as debug

---

bitbots_body_behavior/bitbots_body_behavior/actions/change_action.py
bitbots_body_behavior/bitbots_body_behavior/actions/change_role.py
bitbots_body_behavior/bitbots_body_behavior/actions/deactivate_hcm.py

the module path was incorrect in some actions leading to issues in setup of the DSD tree
This is only an issue since the pre-commit cleanup, for some reason.

fix(actions): import path of dsd `AbstractActionsElemett`
