bit-bots/bitbots_behavior

bitbots_head_behavior/config/head_config.yaml, bitbots_head_behavior/src/bitbots_head_behavior/actions/look_at.py, bitbots_head_behavior/src/bitbots_head_behavior/actions/track_ball.py
This commit addresses #2. It sets deltas for the head movement to prevent unnecessary small movements of the head to track the ball. 
This is NOT tested. The parameters (currently set to 4) are NOT evaluated and just guessed.
=> Reduced head movement

bitbots_blackboard/src/bitbots_blackboard/blackboard.py, bitbots_body_behavior/config/body_behavior.yaml, bitbots_body_behavior/src/bitbots_body_behavior/decisions/ball_dangerous.py
This PR provides an initial implementation of the BallDangerous decision. It evaluates whether the ball is in an area around the goal, which is defined by a parameter. 
The parameter has to be evaluated.
We might need a version which does not require global localization. but it would be quite hard to do this properly.
Of course, this is currently untested. :stuck_out_tongue:
=> initial implementation of BallDangerous

bitbots_body_behavior/config/body_behavior.yaml, bitbots_body_behavior/src/bitbots_body_behavior/actions/kick_ball.py, bitbots_body_behavior/src/bitbots_body_behavior/decisions/ball_kick_area.py, bitbots_body_behavior/src/bitbots_body_behavior/main.dsd
The improved kick decision allows us to define an area for each foot in which the ball can be reached. The areas would replace the evaluation done solely based on the distance (independent to the direction) between robot and ball. 
In case the distance to the ball is too high, the decision returns 'FAR'. I do not like the fact, that therefore I had to move the goToBall stuff into the kickBall function. Thus, it will be harder to implement an alignment to something else than the opponent's goal. 
Maybe, the best way to handle this would be to rename the goToBall action to something like 'goToBallGoalOriented' to reflect the alignment and to rename 'kickBall' to 'kickBallToGoal'
This is not tested.
=> Improved kick decision

bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py, bitbots_body_behavior/src/bitbots_body_behavior/body_behavior.py
Now the behavior processes goal parts (currently only the posts) instead of a goal message. This is necessary due to bit-bots/bitbots_vision#69. Now the world model capsule is also responsible to interpret the different goal posts as one goal.
=> Add goal parts instead of goals

bitbots_blackboard/src/bitbots_blackboard/capsules/pathfinding_capsule.py, bitbots_body_behavior/src/bitbots_body_behavior/actions/stand.py, bitbots_body_behavior/src/bitbots_body_behavior/body_behavior.py
We used to stop by setting our current position as goal position in the path finding. In contrast to the simulation, this does not work in reality (reality sucks) so now, an alternate implementation cancels the current goal in the move_base.
=> body behavior: fixes stop

bitbots_blackboard/package.xml, bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py, bitbots_body_behavior/package.xml, bitbots_body_behavior/src/bitbots_body_behavior/actions/kick_ball.py
solves the bug of doing double kick by forgetting, that we saw the ball after performing a kick. previously the robot did another kick, since it thought that the ball is still there, since the time was not so long since it saw the ball
=> body behavior: solve double kick bug

bitbots_head_behavior/config/head_config.yaml, bitbots_head_behavior/package.xml, bitbots_head_behavior/src/bitbots_head_behavior/actions/look_at.py, bitbots_head_behavior/src/bitbots_head_behavior/head_node.py
With the increased vision fps, we can track balls quite faster. To do this, the head behavior speed needs to be increased slightly.
- Increase DSD refresh rate to roughly the framerate of the vision
- With the old tf buffer fixed, the min delta values for a movement can also be increased.
- Turn up the motor speeds.
=> Config values for faster tracking

bitbots_body_behavior/launch/rviz_behavior_test.launch, bitbots_body_behavior/package.xml
Currently, only the kick node is included in the rviz_behavior_test launch file. This should be changed to the kick launch file.
https://github.com/bit-bots/bitbots_motion/pull/150
=> use kick launch file in rviz_behavior_test

bitbots_blackboard/package.xml, bitbots_blackboard/src/bitbots_blackboard/blackboard.py, bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py, bitbots_body_behavior/config/body_behavior.yaml, bitbots_body_behavior/package.xml, bitbots_body_behavior/src/bitbots_body_behavior/body_behavior.py, bitbots_body_behavior/src/bitbots_body_behavior/decisions/localization.py
Create a localization precision measurement, which allows the BodyBehavior to decide dynamically whether to use the Localization or not.
Issue #72 requests this feature. After merging this, we will need to find good values for the thresholds before closing it.
=> BodyBehavior: localization precision measurement

bitbots_body_behavior/package.xml, bitbots_body_behavior/src/bitbots_body_behavior/decisions/aligned_to_goal.py
I got a NoneType error while testing because the value of a function was re-requested after a None-check. Now, we use the same value for the test as well as the computations
=> Fix a race condition in aligned to goal

bitbots_blackboard/package.xml, bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py, bitbots_body_behavior/config/body_behavior.yaml
Track the ball in the odom frame or in the map frame depending on the precision of the odometry.
Solves #33. Waits for #72 .
The ball should be saved in the map- as well as the odom-frame, so we can decide which to use based on the current state of the localization.
=> Ball tracking

bitbots_blackboard/package.xml, bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py
This fixes some problems related to transforms of ball and goal positions. The fix is that the current timestamp should be used to transform the object in map space back to the base footprint instead of the timestamp where the object was observed.
This closes #99.
=> Fix movement of ball/goal relative to robot

bitbots_body_behavior/launch/rviz_behavior_test.launch, bitbots_body_behavior/package.xml
This fixes the launch file for the behavior test to use the new `viz` parameter for the hcm launch file. The motor goal viz helper is moved up to be launched before the hcm.
=> Fix launch file for behavior test

bitbots_blackboard/package.xml, bitbots_blackboard/src/bitbots_blackboard/blackboard.py, bitbots_blackboard/src/bitbots_blackboard/capsules/pathfinding_capsule.py, bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py, bitbots_body_behavior/config/body_behavior.yaml, bitbots_body_behavior/package.xml
Restructures the params and moves field size definitions into the config yaml.
This solves #12 in a more convenient way.
=> Param restructure

bitbots_body_behavior/src/bitbots_body_behavior/body_behavior.py
This animation client is unused, there is another one in the blackboard that is used.
=> remove unused animation server variable

bitbots_blackboard/src/bitbots_blackboard/capsules/head_capsule.py, bitbots_head_behavior/CMakeLists.txt, bitbots_head_behavior/config/head_config.yaml, bitbots_head_behavior/include/bitbots_head_behavior/collision_checker.h, bitbots_head_behavior/launch/head_behavior_standalone.launch, bitbots_head_behavior/launch/test.launch, bitbots_head_behavior/package.xml, bitbots_head_behavior/src/bitbots_head_behavior/actions/search_pattern.py, bitbots_head_behavior/src/bitbots_head_behavior/actions/search_recent_ball.py, bitbots_head_behavior/src/bitbots_head_behavior/head_node.py, bitbots_head_behavior/src/collision_checker.cpp
This pull request introduces a cpp python module that can check for collisions using MoveIt. When a collision occurs, the head stops moving. In general, it works very well. There are still two issues:
- The collision model of the head should be adapted to include the part between the sides just in front of the camera. Currently, the head can get stuck when a bumper is in that space because it can no longer move away.
- Collisions with the arms are not detected yet. This would be possible by listening to `/joint_states`.
The PR is ready to be tested on the robot (I tested it in rViz).
The pull request closes #55.
=> head behavior: add collision checking module

bitbots_body_behavior/config/body_behavior.yaml, bitbots_body_behavior/src/bitbots_body_behavior/decisions/aligned_to_goal.py, bitbots_body_behavior/src/bitbots_body_behavior/main.dsd
Using the new aligned to goal decision estimates whether a kick would end up in the goal or not. This is only used when a localization (and thereby map goal) is available
=> New decision deciding whether robot is aligned to goal

bitbots_body_behavior/config/body_behavior.yaml, bitbots_body_behavior/scripts/show_world_model_objects.py, bitbots_body_behavior/src/bitbots_body_behavior/decisions/ball_kick_area.py, bitbots_body_behavior/src/bitbots_body_behavior/main.dsd
This pull request merges the kick areas for left and right so that the behavior does not struggle between the two. The dynamic kick takes the ball direction directly, so the resulting action is the same.
Closes #145.
=> Merge ball kick areas

bitbots_body_behavior/config/body_behavior.yaml, bitbots_body_behavior/src/bitbots_body_behavior/main.dsd
After transitioning from the gamestate `init` to `ready`, the robot now waits for 4 (approx. 1 search pattern) seconds before moving to the ready position
Closes bit-bots/bitbots_navigation#113
~- [ ] Run `catkin build`~
~- [ ] Write documentation~
~- [ ] Create issues for future work~
~- [ ] Test on the robot~
=> body_behavior: Wait before positioning ready

bitbots_body_behavior/config/body_behavior.yaml, bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_role_position.py
Lets center offense player got close to the ball when we have kickoff
=> fix go to kickoff position

bitbots_blackboard/src/bitbots_blackboard/capsules/game_status_capsule.py, bitbots_body_behavior/src/bitbots_body_behavior/decisions/goal_scored.py
#180 does not work when the ros time is less than one day because ros times may not be negative, which would happen in `rospy.Time.now() - self.last_goal_from_us_time` when the second is at its default value of one day. This fixes the issue.
Please test this again because on my machine at least the cheering animation is interrupted, possibly because it pops itself from the stack. But this also happens on master, so it is probably an issue with my setup.
=> Fix goal scored decision in simulation time

bitbots_blackboard/src/bitbots_blackboard/blackboard.py, bitbots_body_behavior/config/animations.yaml, bitbots_body_behavior/src/bitbots_body_behavior/actions/get_walkready.py, bitbots_body_behavior/src/bitbots_body_behavior/actions/kick_ball.py, bitbots_body_behavior/src/bitbots_body_behavior/actions/play_animation.py, bitbots_body_behavior/src/bitbots_body_behavior/body_behavior.py, bitbots_body_behavior/src/bitbots_body_behavior/decisions/is_penalty_shoot_robot.py, bitbots_body_behavior/src/bitbots_body_behavior/main.dsd
With this change, after penalty and in initial, we wait for one second before we go to walkready. This is necessary because we are not allowed to move our motors for the first second in these situations, so we cannot immediately start to go to walkready.
Follow-up on #198.
=> StandAndWait after penalty and in initial

bitbots_body_behavior/src/bitbots_body_behavior/actions/stand.py, bitbots_body_behavior/src/bitbots_body_behavior/main.dsd
Make penalty kicker wait a bit before kicking, so that goalies which just throw themselves without actually looking at the ball get a penalty before.
=> add random time for penalty kicker

bitbots_blackboard/src/bitbots_blackboard/capsules/pathfinding_capsule.py, bitbots_body_behavior/config/body_behavior.yaml, bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_defense_position.py, bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_role_position.py, bitbots_body_behavior/src/bitbots_body_behavior/actions/publish_keep_out_area.py, bitbots_body_behavior/src/bitbots_body_behavior/body_behavior.py, bitbots_body_behavior/src/bitbots_body_behavior/decisions/do_once.py, bitbots_body_behavior/src/bitbots_body_behavior/decisions/kick_off_time_up.py, bitbots_body_behavior/src/bitbots_body_behavior/main.dsd
Improves placing positions of the field player and publishes keep out area during placing so that we are not to close to the ball when placing ends.
needs https://github.com/bit-bots/bitbots_navigation/pull/142
Keep out area obstacles are published but somehow not used in costmap. I don't know why. It is deactivated for now anyway since we would have issues when we are inside the obstacle. I open an issue for that so that we can do it after the competition
=> Better placing fieldplayer

bitbots_body_behavior/CMakeLists.txt, bitbots_body_behavior/package.xml, bitbots_body_behavior/test/rostests/test_dsd_file.launch, bitbots_body_behavior/test/rostests/test_dsd_file.py
This adds a very simple test to the behavior. While it does not execute any actual code of the behavior, the dsd file is created and an instance of the blackboard is created. This makes sure that
- the dsd file is valid
- all actions and decisions in the dsd file exist
- all parameters accessed in the blackboard are set in the behavior config
If any of these conditions is not fulfilled, an exception is raised, therefore no asserts are necessary.
This test would have caught the issue that led to us not playing in the games TEST72 and TEST75.
=> Add simple static test for behavior

bitbots_body_behavior/config/body_behavior.yaml
This PR reduces the ball approach distance to avoid problems where the ball is too far for the kick area but too close to walk closer.
=> Reduce ball approach distance

bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py, bitbots_body_behavior/config/body_behavior.yaml
if the ball could not be transformed into the map frame due to the localization not being available, the return value was None which lead to a crash.
=> robustness against no localization tf

bitbots_body_behavior/src/bitbots_body_behavior/main.dsd
Currently, the hybrid goalie always goes to the block position (i.e. in the goal) during the placing phase of free kicks. This pull request changes the behavior to go to the defense position instead when the ball is far enough away from the goal.
=> Fix hybrid goalie in free kick placing

bitbots_body_behavior/src/bitbots_body_behavior/main.dsd
If the goalie runs back to their goal in Normal, they just execute go to role position. We should also look the field features meanwhile.
=> if goalie doesn't see ball, still look at field features

bitbots_body_behavior/src/bitbots_body_behavior/main.dsd
Changes a decision in the main.dsd that keeps the robot from changing between walkready and init pose during init
=> Fix switching between walkready and init in init phase

bitbots_blackboard/src/bitbots_blackboard/capsules/world_model_capsule.py, bitbots_body_behavior/src/bitbots_body_behavior/actions/forget_ball.py, bitbots_body_behavior/src/bitbots_body_behavior/actions/kick_ball.py
The ball filter resets the ball correctly and publishes a filtered ball at the same position but with a high covariance.
The behavior afterwards just ignored the new ball because of it's high covariance, but did not reset / forget the old internal ball.
This fixes the issue by forgetting the ball after receiving a incoming ball with high covariance.
#233
=> Fix forget ball

bitbots_body_behavior/config/body_behavior.yaml
Have our supporter stand slightly further back if we have kickoff so they don't slowly walk onto the enemy side and get penalized.
=> have supporter start out slightly further back

bitbots_body_behavior/src/bitbots_body_behavior/actions/go_to_defense_position.py, bitbots_body_behavior/src/bitbots_body_behavior/actions/turn.py, bitbots_body_behavior/src/bitbots_body_behavior/main.dsd
* Cleanup deprecated dsd parameters (use_time_to_ball was removed previously)
* Go further back if the enemy team has a freekick (we got taken out quite often for that)
* Add action which turns the robot around so it faces its own half (currently unused but was used for testing and it may be helpful in the future)
* Reduce the active area of the defender
* Supporter stops being the defender if the goalie handles the ball (what was the intention for this feature?)
* Stop if localization is unreliable (in contrast to playing with the no localization behavior which disturbs the other players and is completely untested.)
* The defender was a bit weird previously, as its behavior consisted of waiting at the defense position until he is the closest to the ball and then kicking the ball towards …
=> Fix enemy freekick behavior, defender, no localization policy.

bitbots_body_behavior/bitbots_body_behavior/actions/deactivate_hcm.py, bitbots_body_behavior/bitbots_body_behavior/actions/go_to_defense_position.py
The dictionary was not build that way. Instead of having 'defense' as a key, it has 'defense_0' and so on. 
I tested it in the simulation with the fix and the error did not occur again.
And also the way the Quaternion was initialized before did not seem to work.
=> Fix defense position

bitbots_blackboard/bitbots_blackboard/capsules/head_capsule.py, bitbots_blackboard/bitbots_blackboard/capsules/team_data_capsule.py, bitbots_blackboard/bitbots_blackboard/capsules/world_model_capsule.py, bitbots_body_behavior/scripts/backup_behavior.py, bitbots_head_behavior/bitbots_head_behavior/actions/search_pattern.py, bitbots_head_behavior/bitbots_head_behavior/actions/search_recent_ball.py, bitbots_head_behavior/bitbots_head_behavior/actions/visual_compass_record.py
Instead of using `math.sqrt( x**2 + y**2)`, math.hypot(x,y) is now used
=> refactor to math.hypot

bitbots_body_behavior/config/body_behavior.yaml
- Removes unused `goal_width` parameter from config
- This parameter is unused, since we query it from the parameter blackboard (this commit: 73d5114)
=> Refactor: Remove unused goal width parameter from config

bitbots_blackboard/bitbots_blackboard/capsules/animation_capsule.py, bitbots_body_behavior/bitbots_body_behavior/actions/get_walkready.py
This PR fixes the `get_walkready` action in the body_behavoir.
This didn't always work correctly since the ROS2 migration.
=> Fix get_walkready action

bitbots_body_behavior/bitbots_body_behavior/actions/go_to_block_position.py
- Pose-quaternion now gets filled with floats instead of (possibly) ints.
Fixes #298
=> Fix #298: Action: go to block position: Quaternion error

bitbots_blackboard/bitbots_blackboard/capsules/team_data_capsule.py, bitbots_blackboard/bitbots_blackboard/capsules/world_model_capsule.py
This PR is part of a larger refactoring regarding the ball handling in the behavior. As this proposed change is urgent, we want to merge this first. I will propose the refactoring PR later.
- Fixes error in the `world_module_capsule`, where the two different `Time` implementation could not be compared.
Fixes #297
=> Fix #297: Team ball handling in world_model_capusule

bitbots_blackboard/bitbots_blackboard/blackboard.py, bitbots_body_behavior/bitbots_body_behavior/actions/go_to_corner_kick_position.py, bitbots_body_behavior/bitbots_body_behavior/actions/head_modes.py, bitbots_body_behavior/bitbots_body_behavior/body_behavior.py, bitbots_body_behavior/bitbots_body_behavior/main.dsd, bitbots_body_behavior/launch/behavior.launch, bitbots_head_mover/CMakeLists.txt, bitbots_head_mover/config/head_config.yml, bitbots_head_mover/package.xml, bitbots_head_mover/src/move_head.cpp
Interface of head behavior changed due to #295 
The behavior does not crash, but has weird behavior sometimes. But it seems similar to the one the robot is doing when on the master branch.
=> Adjust body behavior to head mover

bitbots_body_behavior/bitbots_body_behavior/actions/head_modes.py, bitbots_body_behavior/bitbots_body_behavior/main.dsd
Fixed the look at action and added the looking at ball before dribbling and doing the look at front pattern afterwards.
=> Use look at ball before dribble

bitbots_blackboard/bitbots_blackboard/blackboard.py, bitbots_body_behavior/bitbots_body_behavior/actions/play_animation.py, bitbots_body_behavior/bitbots_body_behavior/main.dsd
The init animation should only be played in simulation when the robot is reset. In real life, it must not be used because it makes the robot fall.
=> Only play init animation when in simulation

bitbots_body_behavior/bitbots_body_behavior/actions/turn.py, bitbots_body_behavior/bitbots_body_behavior/main.dsd
Turn left using cmd vel if no ball is found
=> Turn left using cmd_vel instead of path planning
